#pragma once

enum SCENE_TYPE
{
	PLAYSCENE_TYPE_TRISTRAM,
	PLAYSCENE_TYPE_CATHEDRAL_F1,
	PLAYSCENE_TYPE_CATHEDRAL_F2,
	PLAYSCENE_TYPE_CATHEDRAL_F3,
	PLAYSCENE_TYPE_CATHEDRAL_F4,
	PLAYSCENE_TYPE_ROYAL_CHAMBER,
	PLAYSCENE_TYPE_REORIK_MANSION,
	PLAYSCENE_TYPE_END
};

enum LAYER_TYPE
{
	LAYER_TYPE_CAMERA,
	LAYER_TYPE_LIGHT,
	LAYER_TYPE_MOUSE,
	LAYER_TYPE_DROP,
	LAYER_TYPE_UI,
	LAYER_TYPE_MODEL,
	LAYER_TYPE_EFFECT,
	LAYER_TYPE_NPC,
	LAYER_TYPE_STATIC_PROB,
	LAYER_TYPE_DYNAMIC_PROB,
	LAYER_TYPE_MONSTER,
	LAYER_TYPE_PLAYER,
	LAYER_TYPE_FOLLOWER,
	LAYER_TYPE_ITEM,
	LAYER_TYPE_MAP,
	LAYER_TYPE_TRIGGER,
	LAYER_TYPE_SKYBOX,
	LAYER_TYPE_BACK,
	LAYER_TYPE_END
};

enum OBJ_TYPE
{
	OBJ_TYPE_STATIC,
	OBJ_TYPE_DYNAMIC
};

enum COM_TYPE
{
	COM_TYPE_UPDATE,
	COM_TYPE_RENDER,
	COM_TYPE_COLLISION,
	COM_TYPE_PATH_FIND,
	COM_TYPE_TRANSFORM,
	COM_TYPE_MATERIAL,
	COM_TYPE_BUFFER,
	COM_TYPE_END
};

enum BUF_TYPE
{
	BUF_TYPE_STATIC_MESH,
	BUF_TYPE_DYNAMIC_MESH,
	BUF_TYPE_TRAIL,
	BUF_TYPE_SCREEN,
	BUF_TYPE_CUBE,
	BUF_TYPE_RECT,
	BUF_TYPE_ENERGY,
	BUF_TYPE_PARTICLE,
	BUF_TYPE_END
};

enum UPDATE_TYPE
{
	UPDATE_TYPE_CAMERA,
	UPDATE_TYPE_LIGHT,
	UPDATE_TYPE_MOUSE,
	UPDATE_TYPE_UI,
	UPDATE_TYPE_DROP,
	UPDATE_TYPE_MODEL,
	UPDATE_TYPE_EFFECT,
	UPDATE_TYPE_NPC,
	UPDATE_TYPE_STATIC_PROB,
	UPDATE_TYPE_DYNAMIC_PROB,
	UPDATE_TYPE_MONSTER,
	UPDATE_TYPE_PLAYER,
	UPDATE_TYPE_FOLLOWER,
	UPDATE_TYPE_ITEM,
	UPDATE_TYPE_MAP,
	UPDATE_TYPE_TRIGGER,
	UPDATE_TYPE_SKYBOX,
	UPDATE_TYPE_BACK,
	UPDATE_TYPE_END
};

enum RENDER_TYPE
{
	RENDER_TYPE_BACK,
	RENDER_TYPE_SKYBOX,
	RENDER_TYPE_TRIGGER,
	RENDER_TYPE_MAP,
	RENDER_TYPE_ITEM,
	RENDER_TYPE_FOLLOWER,
	RENDER_TYPE_PLAYER,
	RENDER_TYPE_MONSTER,
	RENDER_TYPE_DYNAMIC_PROB,
	RENDER_TYPE_STATIC_PROB,
	RENDER_TYPE_NPC,
	RENDER_TYPE_EFFECT,
	RENDER_TYPE_MODEL,
	RENDER_TYPE_DROP,
	RENDER_TYPE_UI,
	RENDER_TYPE_MOUSE,
	RENDER_TYPE_END
};

enum SHADER_TYPE
{
	SHADER_TYPE_SHADOW,
	SHADER_TYPE_VELOCITY,
	SHADER_TYPE_BLUR,
	SHADER_TYPE_BACK,
	SHADER_TYPE_SKYBOX,
	SHADER_TYPE_MESH,
	SHADER_TYPE_LIGHT,
	SHADER_TYPE_FOG,
	SHADER_TYPE_HDR,
	SHADER_TYPE_SSAO,
	SHADER_TYPE_EFFECT,
	SHADER_TYPE_BLEND,
	SHADER_TYPE_UI,
	SHADER_TYPE_MOUSE,
	SHADER_TYPE_END
};

enum TARGET_TYPE
{
	TARGET_TYPE_BLUR,
	TARGET_TYPE_SHADOW_MAP,
	TARGET_TYPE_VELOCITY,
	TARGET_TYPE_DEPTH,
	TARGET_TYPE_ALBEDO,
	TARGET_TYPE_NORMAL,
	TARGET_TYPE_SPECULAR,
	TARGET_TYPE_SHADE,
	TARGET_TYPE_FOG,
	TARGET_TYPE_SSAO,
	TARGET_TYPE_SSAO_GRAY,
	TARGET_TYPE_SSAO_BLUR,
	TARGET_TYPE_HDR,
	TARGET_TYPE_HDR_LUMINANCE_LV1,
	TARGET_TYPE_HDR_LUMINANCE_LV2,
	TARGET_TYPE_HDR_LUMINANCE_LV3,
	TARGET_TYPE_HDR_LUMINANCE_LV4,
	TARGET_TYPE_HDR_LUMINANCE_LV5,
	TARGET_TYPE_HDR_LUMINANCE_LV6,
	TARGET_TYPE_HDR_BRIGHT_PASS,
	TARGET_TYPE_HDR_DOWNSAMPLED,
	TARGET_TYPE_HDR_HORIZONTAL_BLUR,
	TARGET_TYPE_HDR_VERTICAL_BLUR,
	TARGET_TYPE_SPECULAR_ACC,
	TARGET_TYPE_EFFECT,
	TARGET_TYPE_EFFECT_DISTORTION,
	TARGET_TYPE_EFFECT_REFRACTION,
	TARGET_TYPE_SHADOW,
	TARGET_TYPE_SHADOW_NEAR,
	TARGET_TYPE_SHADOW_MIDDLE,
	TARGET_TYPE_SHADOW_FAR,
	TARGET_TYPE_END
};

enum LIGHT_TYPE
{
	LIGHT_TYPE_DIRECTION,
	LIGHT_TYPE_POINT,
	LIGHT_TYPE_SPOT,
	LIGHT_TYPE_SHADOW,
	LIGHT_TYPE_TEST,
	LIGHT_TYPE_END
};

enum MONSTER_TYPE
{
	MONSTER_TYPE_BUTCHER,
	MONSTER_TYPE_GHOUL,
	MONSTER_TYPE_SKELETON_ARCHER_BROWN,
	MONSTER_TYPE_SKELETON_ARCHER_MINT,
	MONSTER_TYPE_SKELETON_ARCHER_RED,
	MONSTER_TYPE_SKELETON_AXE_BLUE,
	MONSTER_TYPE_SKELETON_AXE_RED,
	MONSTER_TYPE_SKELETON_KING,
	MONSTER_TYPE_SKELETON_ONEHAND_BLUE,
	MONSTER_TYPE_SKELETON_ONEHAND_BROWN,
	MONSTER_TYPE_SKELETON_ONEHAND_MINT,
	MONSTER_TYPE_SKELETON_SHIELD_BLUE,
	MONSTER_TYPE_SKELETON_SHIELD_BROWN,
	MONSTER_TYPE_SKELETON_SHIELD_MINT,
	MONSTER_TYPE_SKELETON_SHIELD_RED,
	MONSTER_TYPE_SKELETON_SUMMONER_BLUE,
	MONSTER_TYPE_SKELETON_SUMMONER_BROWN,
	MONSTER_TYPE_SKELETON_SUMMONER_RED,
	MONSTER_TYPE_STITCH,
	MONSTER_TYPE_TRIUNE_BERSERKER,
	MONSTER_TYPE_TRIUNE_CULTISTS,
	MONSTER_TYPE_TRIUNE_POSSESSED,
	MONSTER_TYPE_TRIUNE_VESSEL,
	MONSTER_TYPE_WARDEN,
	MONSTER_TYPE_ZOMBIE_FEMALE,
	MONSTER_TYPE_ZOMBIE_MALE,
	MONSTER_TYPE_ZOMBIE_SKINNY_MALE_RED,
	MONSTER_TYPE_ZOMBIE_SKINNY_MALE_WHITE,
	MONSTER_TYPE_END
};

enum POINT_CLASS
{
	POINT_CLASS_ON_LINE,
	POINT_CLASS_LEFT_SIDE,
	POINT_CLASS_RIGHT_SIDE
};

enum LINE_CLASS
{
	LINE_CLASS_COLLINEAR,
	LINE_CLASS_INTERSECT,
	LINE_CLASS_SEGMENT,
	LINE_CLASS_A_BISECT_B,
	LINE_CLASS_B_BISECT_A,
	LINE_CLASS_PARALLEL
};

enum MOVE_CLASS
{
	MOVE_CLASS_NO_PASS,
	MOVE_CLASS_IN_CELL,
	MOVE_CLASS_OUT_CELL
};

enum CELL_SIDE
{
	CELL_SIDE_AB,
	CELL_SIDE_BC,
	CELL_SIDE_CA
};

enum POINT_TYPE
{
	POINT_TYPE_A,
	POINT_TYPE_B,
	POINT_TYPE_C
};

enum PATH_TYPE
{
	PATH_TYPE_MONSTER,
	PATH_TYPE_PLAYER,
	PATH_TYPE_FOLLOWER,
	PATH_TYPE_END
};

enum SLOT_TYPE
{
	// Barbarian
	SLOT_TYPE_BARBARIAN_PRIMARY,				// 주 기술
	SLOT_TYPE_BARBARIAN_SECONDARY,				// 보조 기술
	SLOT_TYPE_BARBARIAN_DEFENSIVE,				// 방어
	SLOT_TYPE_BARBARIAN_MIGHT,					// 무력
	SLOT_TYPE_BARBARIAN_TACTICS,				// 전술
	SLOT_TYPE_BARBARIAN_RAGE,					// 격노

	// DemonHunter
	SLOT_TYPE_DEMONHUNTER_PRIMARY,				// 주 기술
	SLOT_TYPE_DEMONHUNTER_SECONDARY,			// 보조 기술
	SLOT_TYPE_DEMONHUNTER_DEFENSIVE,			// 방어
	SLOT_TYPE_DEMONHUNTER_HUNTING,				// 사냥
	SLOT_TYPE_DEMONHUNTER_DEVICES,				// 장치
	SLOT_TYPE_DEMONHUNTER_ARCHERY,				// 궁술

	// Monk
	SLOT_TYPE_MONK_PRIMARY,						// 주 기술
	SLOT_TYPE_MONK_SECONDARY,					// 보조 기술
	SLOT_TYPE_MONK_DEFENSIVE,					// 방어
	SLOT_TYPE_MONK_TECHNIQUES,					// 무예
	SLOT_TYPE_MONK_FOCUS,						// 집중
	SLOT_TYPE_MONK_MANTRAS,						// 진언

	// WitchDoctor
	SLOT_TYPE_WITCHDOCTOR_PRIMARY,				// 주 기술
	SLOT_TYPE_WITCHDOCTOR_SECONDARY,			// 보조 기술
	SLOT_TYPE_WITCHDOCTOR_DEFENSIVE,			// 방어
	SLOT_TYPE_WITCHDOCTOR_TERROR,				// 공황
	SLOT_TYPE_WITCHDOCTOR_DECAY,				// 부패
	SLOT_TYPE_WITCHDOCTOR_VOODOO,				// 부두

	// Wizard
	SLOT_TYPE_WIZARD_PRIMARY,					// 주 기술
	SLOT_TYPE_WIZARD_SECONDARY,					// 보조 기술
	SLOT_TYPE_WIZARD_DEFENSIVE,					// 방어
	SLOT_TYPE_WIZARD_FORCE,						// 위력
	SLOT_TYPE_WIZARD_CONJURATION,				// 창조
	SLOT_TYPE_WIZARD_MASTERY,					// 통달

	SLOT_TYPE_END
};

enum SLOT_ID
{
	// ALL
	SLOT_ID_BARBARIAN_OPEN,
	SLOT_ID_BARBARIAN_CLOSE,
	SLOT_ID_BARBARIAN_POTION,
	SLOT_ID_DEMONHUNTER_OPEN,
	SLOT_ID_DEMONHUNTER_CLOSE,
	SLOT_ID_DEMONHUNTER_POTION,
	SLOT_ID_MONK_OPEN,
	SLOT_ID_MONK_CLOSE,
	SLOT_ID_MONK_POTION,
	SLOT_ID_WITCHDOCTOR_OPEN,
	SLOT_ID_WITCHDOCTOR_CLOSE,
	SLOT_ID_WITCHDOCTOR_POTION,
	SLOT_ID_WIZARD_OPEN,
	SLOT_ID_WIZARD_CLOSE,
	SLOT_ID_WIZARD_POTION,

	// Barbarian - 주 기술(Primary)
	SLOT_ID_BARBARIAN_BASH,						// 후려치기
	SLOT_ID_BARBARIAN_CLEAVE,					// 가르기
	SLOT_ID_BARBARIAN_FRENZY,					// 광분
	SLOT_ID_BARBARIAN_WEAPON_THROW,				// 무기 투척
	// Barbarian - 보조 기술(Secondary)
	SLOT_ID_BARBARIAN_PUNCH,					// 주먹질
	SLOT_ID_BARBARIAN_NEAR_ATTACK,				// 근거리 공격
	SLOT_ID_BARBARIAN_FAR_ATTACK,				// 원거리 공격
	SLOT_ID_BARBARIAN_MAGIC_ATTACK,				// 마법봉 발사
	SLOT_ID_BARBARIAN_HAMMER_OF_THE_ANCIENTS,	// 선조의 망치
	SLOT_ID_BARBARIAN_REND,						// 분쇄
	SLOT_ID_BARBARIAN_SEISMIC_SLAM,				// 대지 강타
	SLOT_ID_BARBARIAN_WHIRLWIND,				// 소용돌이
	SLOT_ID_BARBARIAN_ANCIENT_SPEAR,			// 고대의 작살
	// Barbarian - 방어(Defensive)
	SLOT_ID_BARBARIAN_GROUND_STOMP,				// 발 구르기
	SLOT_ID_BARBARIAN_LEAP,						// 도약 공격
	SLOT_ID_BARBARIAN_SPRINT,					// 질주
	SLOT_ID_BARBARIAN_IGNORE_PAIN,				// 고통 감내
	// Barbarian - 무력(Might)
	SLOT_ID_BARBARIAN_OVERPOWER,				// 제압
	SLOT_ID_BARBARIAN_REVENGE,					// 보복
	SLOT_ID_BARBARIAN_FURIOUS_CHARGE,			// 맹렬한 돌진
	// Barbarian - 전술(Tactics)
	SLOT_ID_BARBARIAN_THREATENING_SHOUT,		// 위협의 외침
	SLOT_ID_BARBARIAN_BATTLE_RAGE,				// 전투 격노
	SLOT_ID_BARBARIAN_WAR_CRY,					// 전장의 함성
	// Barbarian - 격노(Rage)
	SLOT_ID_BARBARIAN_EARTHQUAKE,				// 지진
	SLOT_ID_BARBARIAN_CALL_OF_THE_ANCIENTS,		// 선조의 귀환
	SLOT_ID_BARBARIAN_WRATH_OF_THE_BERSERKER,	// 광전사의 진노

	// DemonHunter - 주 기술(Primary)
	SLOT_ID_DEMONHUNTER_HUNGERING_ARROW,		// 굶주린 화살
	SLOT_ID_DEMONHUNTER_ENTANGLING_SHOT,		// 속박탄
	SLOT_ID_DEMONHUNTER_BOLA,					// 올가미
	SLOT_ID_DEMONHUNTER_EVASIVE_FIRE,			// 회피사격
	SLOT_ID_DEMONHUNTER_GRENADES,				// 수류탄
	// DemonHunter - 보조 기술(Secondary)
	SLOT_ID_DEMONHUNTER_PUNCH,					// 주먹질
	SLOT_ID_DEMONHUNTER_NEAR_ATTACK,			// 근거리 공격
	SLOT_ID_DEMONHUNTER_FAR_ATTACK,				// 원거리 공격
	SLOT_ID_DEMONHUNTER_MAGIC_ATTACK,			// 마법봉 발사
	SLOT_ID_DEMONHUNTER_IMPALE,					// 투검
	SLOT_ID_DEMONHUNTER_RAPID_FIRE,				// 연발 사격
	SLOT_ID_DEMONHUNTER_CHAKRAM,				// 회전 표창
	SLOT_ID_DEMONHUNTER_ELEMENTAL_ARROW,		// 원소화살
	// DemonHunter - 방어(Defensive)
	SLOT_ID_DEMONHUNTER_CALTROPS,				// 쇠못 덫
	SLOT_ID_DEMONHUNTER_SMOKE_SCREEN,			// 연막
	SLOT_ID_DEMONHUNTER_SHADOW_POWER,			// 어둠의 힘
	// DemonHunter - 사냥(Hunting)
	SLOT_ID_DEMONHUNTER_VAULT,					// 도약
	SLOT_ID_DEMONHUNTER_PREPARATION,			// 전투 준비
	SLOT_ID_DEMONHUNTER_COMPANION,				// 동료
	SLOT_ID_DEMONHUNTER_MARKED_FOR_DEATH,		// 죽음의 표식
	// DemonHunter - 장치(Devices)
	SLOT_ID_DEMONHUNTER_FAN_OF_KNIVES,			// 칼날 부채
	SLOT_ID_DEMONHUNTER_SPIKE_TRAP,				// 쐐기 덫
	SLOT_ID_DEMONHUNTER_SENTRY,					// 자동 쇠뇌
	// DemonHunter - 궁술(Archery)
	SLOT_ID_DEMONHUNTER_STRAFE,					// 난사
	SLOT_ID_DEMONHUNTER_MULTISHOT,				// 다발 사격
	SLOT_ID_DEMONHUNTER_CLUSTER_ARROW,			// 확산탄
	SLOT_ID_DEMONHUNTER_RAIN_OF_VENGEANCE,		// 복수의 비

	// Monk - 주 기술(Primary)
	SLOT_ID_MONK_FISTS_OF_THUNDER,				// 천둥주먹
	SLOT_ID_MONK_DEADLY_REACH,					// 연속 격파
	SLOT_ID_MONK_CRIPPLING_WAVE,				// 마비의 파동
	SLOT_ID_MONK_WAY_OF_THE_HUNDRED_FISTS,		// 천지권법
	// Monk - 보조 기술(Secondary)
	SLOT_ID_MONK_PUNCH,							// 주먹질
	SLOT_ID_MONK_NEAR_ATTACK,					// 근거리 공격
	SLOT_ID_MONK_FAR_ATTACK,					// 원거리 공격
	SLOT_ID_MONK_MAGIC_ATTACK,					// 마법봉 발사
	SLOT_ID_MONK_LASHING_TAIL_KICK,				// 반달차기
	SLOT_ID_MONK_TEMPEST_RUSH,					// 폭풍 질주
	SLOT_ID_MONK_WAVE_OF_LIGHT,					// 빛의 파동
	// Monk - 방어(Defensive)
	SLOT_ID_MONK_BLINDING_FLASH,				// 눈부신 섬광
	SLOT_ID_MONK_BREATH_OF_HEAVEN,				// 천상의 숨결
	SLOT_ID_MONK_SERENITY,						// 평안
	SLOT_ID_MONK_INNER_SANCTUARY,				// 내면의 안식처
	// Monk - 무예(Techniques)
	SLOT_ID_MONK_DASHING_STRIKE,				// 진격타
	SLOT_ID_MONK_EXPLODING_PALM,				// 폭발 장법
	SLOT_ID_MONK_SWEEPING_WIND,					// 휘몰이
	// Monk - 집중(Focus)
	SLOT_ID_MONK_CYCLONE_STRIKE,				// 용오름
	SLOT_ID_MONK_SEVEN_SIDED_STRIKE,			// 칠면 공격
	SLOT_ID_MONK_MYSTIC_ALLY,					// 신기한 벗
	// Monk - 진언(Mantras)
	SLOT_ID_MONK_MANTRA_OF_SALVATION,			// 구원의 진언
	SLOT_ID_MONK_MANTRA_OF_RETRIBUTION,			// 응보의 진언
	SLOT_ID_MONK_MANTRA_OF_HEALING,				// 치유의 진언
	SLOT_ID_MONK_MANTRA_OF_CONVICTION,			// 신념의 진언

	// WitchDoctor - 주 기술(Primary)
	SLOT_ID_WITCHDOCTOR_POISON_DART,			// 독침
	SLOT_ID_WITCHDOCTOR_CORPSE_SPIDERS,			// 시체 거미
	SLOT_ID_WITCHDOCTOR_PLAGUE_OF_TOADS,		// 역병 두꺼비
	SLOT_ID_WITCHDOCTOR_FIREBOMB,				// 불폭탄
	// WitchDoctor - 보조 기술(Secondary)
	SLOT_ID_WITCHDOCTOR_PUNCH,					// 주먹질
	SLOT_ID_WITCHDOCTOR_NEAR_ATTACK,			// 근거리 공격
	SLOT_ID_WITCHDOCTOR_FAR_ATTACK,				// 원거리 공격
	SLOT_ID_WITCHDOCTOR_MAGIC_ATTACK,			// 마법봉 발사
	SLOT_ID_WITCHDOCTOR_GRASP_OF_THE_DEAD,		// 망자의 손아귀
	SLOT_ID_WITCHDOCTOR_FIREBATS,				// 불박쥐
	SLOT_ID_WITCHDOCTOR_HAUNT,					// 혼령 출몰
	SLOT_ID_WITCHDOCTOR_LOCUST_SWARM,			// 메뚜기 떼
	// WitchDoctor - 방어(Defensive)
	SLOT_ID_WITCHDOCTOR_SUMMON_ZOMBIE_DOGS,		// 좀비 들개 소환
	SLOT_ID_WITCHDOCTOR_HORRIFY,				// 공포
	SLOT_ID_WITCHDOCTOR_SPIRIT_WALK,			// 혼령 걸음
	SLOT_ID_WITCHDOCTOR_HEX,					// 주술
	// WitchDoctor - 공황(Terror)
	SLOT_ID_WITCHDOCTOR_SOUL_HARVEST,			// 혼령 수확
	SLOT_ID_WITCHDOCTOR_SACRIFICE,				// 희생
	SLOT_ID_WITCHDOCTOR_MASS_CONFUSION,			// 대혼란
	// WitchDoctor - 부패(Decay)
	SLOT_ID_WITCHDOCTOR_ZOMBIE_CHARGER,			// 돌진 좀비
	SLOT_ID_WITCHDOCTOR_SPIRIT_BARRAGE,			// 혼령 공세
	SLOT_ID_WITCHDOCTOR_ACID_CLOUD,				// 산성 구름
	SLOT_ID_WITCHDOCTOR_WALL_OF_DEATH,			// 죽음의 벽
	// WitchDoctor - 부두(Voodoo)
	SLOT_ID_WITCHDOCTOR_GARGANTUAN,				// 덩치
	SLOT_ID_WITCHDOCTOR_BIG_BAD_VOODOO,			// 대재앙의 부두술
	SLOT_ID_WITCHDOCTOR_FETISH_ARMY,			// 우상족 군대

	// Wizard - 주 기술(Primary)
	SLOT_ID_WIZARD_MAGIC_MISSILE,				// 마력탄
	SLOT_ID_WIZARD_SHOCK_PULSE,					// 전기 충격
	SLOT_ID_WIZARD_SPECTRAL_BLADE,				// 저승의 칼날
	SLOT_ID_WIZARD_ELECTROCUTE,					// 감전
	// Wizard - 보조 기술(Secondary)
	SLOT_ID_WIZARD_PUNCH,						// 주먹질
	SLOT_ID_WIZARD_NEAR_ATTACK,					// 근거리 공격
	SLOT_ID_WIZARD_FAR_ATTACK,					// 원거리 공격
	SLOT_ID_WIZARD_MAGIC_ATTACK,				// 마법봉 발사
	SLOT_ID_WIZARD_RAY_OF_FROST,				// 서리 광선
	SLOT_ID_WIZARD_ARCANE_ORB,					// 비전 보주
	SLOT_ID_WIZARD_ARCANE_TORRENT,				// 비전 격류
	SLOT_ID_WIZARD_DISINTEGRATE,				// 파열
	// Wizard - 방어(Defensive)
	SLOT_ID_WIZARD_FROST_NOVA,					// 서릿발
	SLOT_ID_WIZARD_DIAMOND_SKIN,				// 다이아몬드 피부
	SLOT_ID_WIZARD_SLOW_TIME,					// 감속 지대
	SLOT_ID_WIZARD_TELEPORT,					// 순간이동
	// Wizard - 위력(Force)
	SLOT_ID_WIZARD_WAVE_OF_FORCE,				// 힘의 파동
	SLOT_ID_WIZARD_ENERGY_TWISTER,				// 마력 돌개 바람
	SLOT_ID_WIZARD_HYDRA,						// 히드라
	SLOT_ID_WIZARD_METEOR,						// 운석 낙하
	SLOT_ID_WIZARD_BLIZZARD,					// 눈보라
	// Wizard - 창조(Conjuration)
	SLOT_ID_WIZARD_ICE_ARMOR,					// 얼음 갑옷
	SLOT_ID_WIZARD_STORM_ARMOR,					// 천둥 갑옷
	SLOT_ID_WIZARD_MAGIC_WEAPON,				// 마법 무기
	SLOT_ID_WIZARD_FAMILIAR,					// 사역마
	SLOT_ID_WIZARD_ENERGY_ARMOR,				// 마력 갑옷
	// Wizard - 통달(Mastery)
	SLOT_ID_WIZARD_EXPLOSIVE_BLAST,				// 에너지 폭발
	SLOT_ID_WIZARD_MIRROR_IMAGE,				// 분신
	SLOT_ID_WIZARD_ARCHON,						// 마인
	
	SLOT_ID_END
};

enum SLOT_RESULT
{
	SLOT_RESULT_NULL,
	SLOT_RESULT_IMPOSSIBLE_WEAFON,
	SLOT_RESULT_IMPOSSIBLE_RANGE,
	SLOT_RESULT_COOLDOWN_TIEM,
	SLOT_RESULT_RAGE_EMPTY,
	SLOT_RESULT_VISION_EMPTY,
	SLOT_RESULT_MANA_EMPTY,
	SLOT_RESULT_EFFORT_EMPTY,
	SLOT_RESULT_CONTROL_EMPTY,
	SLOT_RESULT_HATE_EMPTY,
	SLOT_RESULT_ERROR_PICK,
	SLOT_RESULT_CHARGE_EMPTY,
	SLOT_RESULT_FULL_LIFE,

	SLOT_RESULT_END
};

enum COLL_TYPE
{
	COLL_TYPE_PLAYER,
	COLL_TYPE_MONSTER,
	COLL_TYPE_PLAYER_EFFECT,
	COLL_TYPE_MONSTER_EFFECT,
	COLL_TYPE_NPC,
	COLL_TYPE_PROB,
	COLL_TYPE_END
};

enum WINDOW_TYPE
{
	WINDOW_TYPE_SLOT,
	WINDOW_TYPE_SKILL,
	WINDOW_TYPE_INVENTORY,
	WINDOW_TYPE_STORAGE,
	WINDOW_TYPE_STORE,
	WINDOW_TYPE_FACTORY,
	WINDOW_TYPE_ENCHANT,
	WINDOW_TYPE_SETTING,
	WINDOW_TYPE_QUEST,
	WINDOW_TYPE_ACHIEVE,
	WINDOW_TYPE_DETAIL,
	WINDOW_TYPE_FOLLOWER,
	WINDOW_TYPE_FOLLOWER_DETAIL,
	WINDOW_TYPE_GATE_WAY,

	// Barbarian
	WINDOW_TYPE_BARBARIAN_PRIMARY,				// 주 기술
	WINDOW_TYPE_BARBARIAN_SECONDARY,			// 보조 기술
	WINDOW_TYPE_BARBARIAN_DEFENSIVE,			// 방어
	WINDOW_TYPE_BARBARIAN_MIGHT,				// 무력
	WINDOW_TYPE_BARBARIAN_TACTICS,				// 전술
	WINDOW_TYPE_BARBARIAN_RAGE,					// 격노

	// DemonHunter
	WINDOW_TYPE_DEMONHUNTER_PRIMARY,			// 주 기술
	WINDOW_TYPE_DEMONHUNTER_SECONDARY,			// 보조 기술
	WINDOW_TYPE_DEMONHUNTER_DEFENSIVE,			// 방어
	WINDOW_TYPE_DEMONHUNTER_HUNTING,			// 사냥
	WINDOW_TYPE_DEMONHUNTER_DEVICES,			// 장치
	WINDOW_TYPE_DEMONHUNTER_ARCHERY,			// 궁술

	// Monk
	WINDOW_TYPE_MONK_PRIMARY,					// 주 기술
	WINDOW_TYPE_MONK_SECONDARY,					// 보조 기술
	WINDOW_TYPE_MONK_DEFENSIVE,					// 방어
	WINDOW_TYPE_MONK_TECHNIQUES,				// 무예
	WINDOW_TYPE_MONK_FOCUS,						// 집중
	WINDOW_TYPE_MONK_MANTRAS,					// 진언

	// WitchDoctor
	WINDOW_TYPE_WITCHDOCTOR_PRIMARY,			// 주 기술
	WINDOW_TYPE_WITCHDOCTOR_SECONDARY,			// 보조 기술
	WINDOW_TYPE_WITCHDOCTOR_DEFENSIVE,			// 방어
	WINDOW_TYPE_WITCHDOCTOR_TERROR,				// 공황
	WINDOW_TYPE_WITCHDOCTOR_DECAY,				// 부패
	WINDOW_TYPE_WITCHDOCTOR_VOODOO,				// 부두

	// Wizard
	WINDOW_TYPE_WIZARD_PRIMARY,					// 주 기술
	WINDOW_TYPE_WIZARD_SECONDARY,				// 보조 기술
	WINDOW_TYPE_WIZARD_DEFENSIVE,				// 방어
	WINDOW_TYPE_WIZARD_FORCE,					// 위력
	WINDOW_TYPE_WIZARD_CONJURATION,				// 창조
	WINDOW_TYPE_WIZARD_MASTERY,					// 통달

	WINDOW_TYPE_END
};

enum STATE_TYPE
{
	// DemonHunter_Female
	STATE_TYPE_DEMONHUNTER_FEMALE_ATTACK1,
	STATE_TYPE_DEMONHUNTER_FEMALE_ATTACK2,
	STATE_TYPE_DEMONHUNTER_FEMALE_BACKFLIP,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_ATTACK,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_BOLASLOT,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_BUFF,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_HIT,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_IDLE,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_MULTISHOT,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_RAINOFARROW,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_RUN,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_STUNNED,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_BACKFLIP,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_ATTACK,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_BOLASLOT,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_BUFF,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_HIT,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_IDLE,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_MULTISHOT,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_RAINOFARROW,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_RUN,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_STUNNED,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_BACKFLIP,
	STATE_TYPE_DEMONHUNTER_FEMALE_BUFF,
	STATE_TYPE_DEMONHUNTER_FEMALE_CALTROP,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_ATTACK,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_BOLASLOT,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_BUFF,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_HIT,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_IDLE,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_MULTISHOT,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_RAINOFARROW,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_RUN,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_STUNNED,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_BACKFLIP,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_ATTACK_LEFT,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_ATTACK_RIGHT,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_BOLASLOT,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_BUFF,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_HIT,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_IDLE,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_MULTISHOT,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_RAINOFARROW,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_RUN,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_STUNNED,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_BACKFLIP,
	STATE_TYPE_DEMONHUNTER_FEMALE_COMPANION,	
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_COMPANION,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_COMPANION,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_COMPANION,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_COMPANION,
	STATE_TYPE_DEMONHUNTER_FEMALE_FANOFKNIVES,	
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_FANOFKNIVES,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_FANOFKNIVES,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_FANOFKNIVES,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_FANOFKNIVES,
	STATE_TYPE_DEMONHUNTER_FEMALE_IMPALE,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_IMPALE,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_IMPALE,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_IMPALE,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_IMPALE,
	STATE_TYPE_DEMONHUNTER_FEMALE_STRAFE,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_STRAFE,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_STRAFE,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_STRAFE,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_STRAFE,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_CALTROP,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_CALTROP,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_CALTROP,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_CALTROP,
	STATE_TYPE_DEMONHUNTER_FEMALE_DEATH,
	STATE_TYPE_DEMONHUNTER_FEMALE_HIT,
	STATE_TYPE_DEMONHUNTER_FEMALE_IDLE,	
	STATE_TYPE_DEMONHUNTER_FEMALE_RUN,
	STATE_TYPE_DEMONHUNTER_FEMALE_STUNNED,
	STATE_TYPE_DEMONHUNTER_FEMALE_WAYPOINT,
	
	STATE_TYPE_DEMONHUNTER_FEMALE_MEZ,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_MEZ,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_MEZ,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_MEZ,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_MEZ,
	
	STATE_TYPE_DEMONHUNTER_FEMALE_KNOCKBACK,
	STATE_TYPE_DEMONHUNTER_FEMALE_BOW_KNOCKBACK,
	STATE_TYPE_DEMONHUNTER_FEMALE_BIGBOW_KNOCKBACK,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB1_KNOCKBACK,
	STATE_TYPE_DEMONHUNTER_FEMALE_CB2_KNOCKBACK,


	// Wizard_Female
	STATE_TYPE_WIZARD_FEMALE_STF_SUMMON,
	STATE_TYPE_WIZARD_FEMALE_2HS_SUMMON,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_SUMMON,
	STATE_TYPE_WIZARD_FEMALE_1HS_SUMMON,
	STATE_TYPE_WIZARD_FEMALE_BOW_SUMMON, 
	STATE_TYPE_WIZARD_FEMALE_XBOW_SUMMON, 
	STATE_TYPE_WIZARD_FEMALE_STF_DIRECTED,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_DIRECTED,
	STATE_TYPE_WIZARD_FEMALE_1HS_DIRECTED,
	STATE_TYPE_WIZARD_FEMALE_2HS_DIRECTED, 
	STATE_TYPE_WIZARD_FEMALE_BOW_DIRECTED, 
	STATE_TYPE_WIZARD_FEMALE_XBOW_DIRECTED, 
	STATE_TYPE_WIZARD_FEMALE_STF_CHANNEL,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_CHANNEL,
	STATE_TYPE_WIZARD_FEMALE_1HS_CHANNEL,
	STATE_TYPE_WIZARD_FEMALE_2HS_CHANNEL, 
	STATE_TYPE_WIZARD_FEMALE_BOW_CHANNEL, 
	STATE_TYPE_WIZARD_FEMALE_XBOW_CHANNEL, 
	STATE_TYPE_WIZARD_FEMALE_STF_AOE2,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_AOE2,
	STATE_TYPE_WIZARD_FEMALE_1HS_AOE2,
	STATE_TYPE_WIZARD_FEMALE_2HS_AOE2, 
	STATE_TYPE_WIZARD_FEMALE_BOW_AOE2, 
	STATE_TYPE_WIZARD_FEMALE_XBOW_AOE2, 
	STATE_TYPE_WIZARD_FEMALE_STF_AOE,
	STATE_TYPE_WIZARD_FEMALE_2HS_AOE,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_AOE,
	STATE_TYPE_WIZARD_FEMALE_1HS_AOE,
	STATE_TYPE_WIZARD_FEMALE_BOW_AOE,
	STATE_TYPE_WIZARD_FEMALE_XBOW_AOE,
	STATE_TYPE_WIZARD_FEMALE_XBOW_RUN,
	STATE_TYPE_WIZARD_FEMALE_BOW_RUN,
	STATE_TYPE_WIZARD_FEMALE_2HS_RUN,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_RUN,
	STATE_TYPE_WIZARD_FEMALE_1HS_RUN,
	STATE_TYPE_WIZARD_FEMALE_STF_RUN,
	STATE_TYPE_WIZARD_FEMALE_XBOW_IDLE,
	STATE_TYPE_WIZARD_FEMALE_STF_IDLE,
	STATE_TYPE_WIZARD_FEMALE_BOW_IDLE,
	STATE_TYPE_WIZARD_FEMALE_2HS_IDLE,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_IDLE,
	STATE_TYPE_WIZARD_FEMALE_1HS_IDLE,
	STATE_TYPE_WIZARD_FEMALE_2HS_KNOCKBACK_END,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_KNOCKBACK_END,
	STATE_TYPE_WIZARD_FEMALE_1HS_KNOCKBACK_END,
	STATE_TYPE_WIZARD_FEMALE_STF_KNOCKBACK_END,
	STATE_TYPE_WIZARD_FEMALE_BOW_KNOCKBACK_END,
	STATE_TYPE_WIZARD_FEMALE_XBOW_KNOCKBACK_END,
	STATE_TYPE_WIZARD_FEMALE_2HS_KNOCKBACK,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_KNOCKBACK,
	STATE_TYPE_WIZARD_FEMALE_1HS_KNOCKBACK,
	STATE_TYPE_WIZARD_FEMALE_STF_KNOCKBACK,
	STATE_TYPE_WIZARD_FEMALE_BOW_KNOCKBACK,
	STATE_TYPE_WIZARD_FEMALE_XBOW_KNOCKBACK,
	STATE_TYPE_WIZARD_FEMALE_XBOW_HIT,
	STATE_TYPE_WIZARD_FEMALE_STF_HIT,
	STATE_TYPE_WIZARD_FEMALE_BOW_HIT,
	STATE_TYPE_WIZARD_FEMALE_2HS_HIT,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_HIT,
	STATE_TYPE_WIZARD_FEMALE_1HS_HIT,
	STATE_TYPE_WIZARD_FEMALE_XBOW_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_BOW_RANGE_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_BOW_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_2HS_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_1HS_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_WAND_ORB_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_WAND_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_STF_ATTACK,
	STATE_TYPE_WIZARD_FEMALE_XBOW_RECOLL, 
	STATE_TYPE_WIZARD_FEMALE_STF_RECOLL, 
	STATE_TYPE_WIZARD_FEMALE_BOW_RECOLL, 
	STATE_TYPE_WIZARD_FEMALE_2HS_RECOLL,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_RECOLL,
	STATE_TYPE_WIZARD_FEMALE_1HS_RECOLL,
	STATE_TYPE_WIZARD_FEMALE_XBOW_TELEPORT, 
	STATE_TYPE_WIZARD_FEMALE_STF_TELEPORT, 
	STATE_TYPE_WIZARD_FEMALE_BOW_TELEPORT, 
	STATE_TYPE_WIZARD_FEMALE_2HS_TELEPORT,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_TELEPORT,
	STATE_TYPE_WIZARD_FEMALE_1HS_TELEPORT,
	STATE_TYPE_WIZARD_FEMALE_XBOW_MEZ,
	STATE_TYPE_WIZARD_FEMALE_STF_MEZ,
	STATE_TYPE_WIZARD_FEMALE_BOW_MEZ,
	STATE_TYPE_WIZARD_FEMALE_2HS_MEZ,
	STATE_TYPE_WIZARD_FEMALE_1HS_MEZ,
	STATE_TYPE_WIZARD_FEMALE_1HS_ORB_MEZ,
	


	// BarBarian_male
	STATE_TYPE_BARBARIAN_MALE_1HS_ATTACK,
	STATE_TYPE_BARBARIAN_MALE_1HS_BUFF,
	STATE_TYPE_BARBARIAN_MALE_1HS_CLEAVE01,
	STATE_TYPE_BARBARIAN_MALE_1HS_CLEAVE02,
	STATE_TYPE_BARBARIAN_MALE_1HS_FOOTSTOMP,
	STATE_TYPE_BARBARIAN_MALE_1HS_FURIOUS_CHARGE_END,
	STATE_TYPE_BARBARIAN_MALE_1HS_FURIOUS_CHARGE_LOOP,
	STATE_TYPE_BARBARIAN_MALE_1HS_HIRLWIND,
	STATE_TYPE_BARBARIAN_MALE_1HS_HIRLWIND_END,
	STATE_TYPE_BARBARIAN_MALE_1HS_HIT,
	STATE_TYPE_BARBARIAN_MALE_1HS_IDLE,
	STATE_TYPE_BARBARIAN_MALE_1HS_KNOCKBACK_END,
	STATE_TYPE_BARBARIAN_MALE_1HS_KNOCKBACK_LOOP,
	STATE_TYPE_BARBARIAN_MALE_1HS_LEAPATTACK_AIR,
	STATE_TYPE_BARBARIAN_MALE_1HS_LEAPATTACK_END,
	STATE_TYPE_BARBARIAN_MALE_1HS_PARRY,
	STATE_TYPE_BARBARIAN_MALE_1HS_REVENGE,
	STATE_TYPE_BARBARIAN_MALE_1HS_RUN,
	STATE_TYPE_BARBARIAN_MALE_1HT_ATTACK,
	STATE_TYPE_BARBARIAN_MALE_1HT_BUFF,
	STATE_TYPE_BARBARIAN_MALE_1HT_CLEAVE01,
	STATE_TYPE_BARBARIAN_MALE_1HT_CLEAVE02,
	STATE_TYPE_BARBARIAN_MALE_1HT_FOOTSTOMP,
	STATE_TYPE_BARBARIAN_MALE_1HT_FURIOUS_CHARGE_END,
	STATE_TYPE_BARBARIAN_MALE_1HT_FURIOUS_CHARGE_LOOP,
	STATE_TYPE_BARBARIAN_MALE_1HT_HIRLWIND,
	STATE_TYPE_BARBARIAN_MALE_1HT_HIRLWIND_END,
	STATE_TYPE_BARBARIAN_MALE_1HT_HIT,
	STATE_TYPE_BARBARIAN_MALE_1HT_IDLE,
	STATE_TYPE_BARBARIAN_MALE_1HT_KNOCKBACK_END,
	STATE_TYPE_BARBARIAN_MALE_1HT_KNOCKBACK_LOOP,
	STATE_TYPE_BARBARIAN_MALE_1HT_LEAPATTACK_AIR,
	STATE_TYPE_BARBARIAN_MALE_1HT_LEAPATTACK_END,
	STATE_TYPE_BARBARIAN_MALE_1HT_PARRY,
	STATE_TYPE_BARBARIAN_MALE_1HT_REVENGE,
	STATE_TYPE_BARBARIAN_MALE_1HT_RUN,
	STATE_TYPE_BARBARIAN_MALE_2HS_ATTACK,
	STATE_TYPE_BARBARIAN_MALE_2HS_BUFF,
	STATE_TYPE_BARBARIAN_MALE_2HS_CLEAVE01,
	STATE_TYPE_BARBARIAN_MALE_2HS_CLEAVE02,
	STATE_TYPE_BARBARIAN_MALE_2HS_FOOTSTOMP,
	STATE_TYPE_BARBARIAN_MALE_2HS_FURIOUS_CHARGE_END,
	STATE_TYPE_BARBARIAN_MALE_2HS_FURIOUS_CHARGE_LOOP,
	STATE_TYPE_BARBARIAN_MALE_2HS_HIRLWIND,
	STATE_TYPE_BARBARIAN_MALE_2HS_HIRLWIND_END,
	STATE_TYPE_BARBARIAN_MALE_2HS_HIT,
	STATE_TYPE_BARBARIAN_MALE_2HS_IDLE,
	STATE_TYPE_BARBARIAN_MALE_2HS_KNOCKBACK_END,
	STATE_TYPE_BARBARIAN_MALE_2HS_KNOCKBACK_LOOP,
	STATE_TYPE_BARBARIAN_MALE_2HS_LEAPATTACK_AIR,
	STATE_TYPE_BARBARIAN_MALE_2HS_LEAPATTACK_END,
	STATE_TYPE_BARBARIAN_MALE_2HS_PARRY,
	STATE_TYPE_BARBARIAN_MALE_2HS_REVENGE,
	STATE_TYPE_BARBARIAN_MALE_2HS_RUN,
	STATE_TYPE_BARBARIAN_MALE_2HT_ATTACK,
	STATE_TYPE_BARBARIAN_MALE_2HT_BUFF,
	STATE_TYPE_BARBARIAN_MALE_2HT_CLEAVE01,
	STATE_TYPE_BARBARIAN_MALE_2HT_CLEAVE02,
	STATE_TYPE_BARBARIAN_MALE_2HT_FOOTSTOMP,
	STATE_TYPE_BARBARIAN_MALE_2HT_FURIOUS_CHARGE_END,
	STATE_TYPE_BARBARIAN_MALE_2HT_FURIOUS_CHARGE_LOOP,
	STATE_TYPE_BARBARIAN_MALE_2HT_HIRLWIND,
	STATE_TYPE_BARBARIAN_MALE_2HT_HIRLWIND_END,
	STATE_TYPE_BARBARIAN_MALE_2HT_HIT,
	STATE_TYPE_BARBARIAN_MALE_2HT_IDLE,
	STATE_TYPE_BARBARIAN_MALE_2HT_KNOCKBACK_END,
	STATE_TYPE_BARBARIAN_MALE_2HT_KNOCKBACK_LOOP,
	STATE_TYPE_BARBARIAN_MALE_2HT_LEAPATTACK_AIR,
	STATE_TYPE_BARBARIAN_MALE_2HT_LEAPATTACK_END,
	STATE_TYPE_BARBARIAN_MALE_2HT_PARRY,
	STATE_TYPE_BARBARIAN_MALE_2HT_REVENGE,
	STATE_TYPE_BARBARIAN_MALE_2HT_RUN,
	STATE_TYPE_BARBARIAN_MALE_STF_ATTACK,
	STATE_TYPE_BARBARIAN_MALE_STF_BUFF,
	STATE_TYPE_BARBARIAN_MALE_STF_CLEAVE01,
	STATE_TYPE_BARBARIAN_MALE_STF_CLEAVE02,
	STATE_TYPE_BARBARIAN_MALE_STF_FOOTSTOMP,
	STATE_TYPE_BARBARIAN_MALE_STF_FURIOUS_CHARGE_END,
	STATE_TYPE_BARBARIAN_MALE_STF_FURIOUS_CHARGE_LOOP,
	STATE_TYPE_BARBARIAN_MALE_STF_HIRLWIND,
	STATE_TYPE_BARBARIAN_MALE_STF_HIRLWIND_END,
	STATE_TYPE_BARBARIAN_MALE_STF_HIT,
	STATE_TYPE_BARBARIAN_MALE_STF_IDLE,
	STATE_TYPE_BARBARIAN_MALE_STF_KNOCKBACK_END,
	STATE_TYPE_BARBARIAN_MALE_STF_KNOCKBACK_LOOP,
	STATE_TYPE_BARBARIAN_MALE_STF_LEAPATTACK_AIR,
	STATE_TYPE_BARBARIAN_MALE_STF_LEAPATTACK_END,
	STATE_TYPE_BARBARIAN_MALE_STF_PARRY,
	STATE_TYPE_BARBARIAN_MALE_STF_REVENGE,
	STATE_TYPE_BARBARIAN_MALE_STF_RUN,
	STATE_TYPE_BARBARIAN_MALE_DW_ATTACK_L,
	STATE_TYPE_BARBARIAN_MALE_DW_ATTACK_R,
	STATE_TYPE_BARBARIAN_MALE_DW_BUFF,
	STATE_TYPE_BARBARIAN_MALE_DW_CLEAVE01,
	STATE_TYPE_BARBARIAN_MALE_DW_CLEAVE02,
	STATE_TYPE_BARBARIAN_MALE_DW_FOOTSTOMP,
	STATE_TYPE_BARBARIAN_MALE_DW_FURIOUS_CHARGE_END,
	STATE_TYPE_BARBARIAN_MALE_DW_FURIOUS_CHARGE_LOOP,
	STATE_TYPE_BARBARIAN_MALE_DW_HIRLWIND,
	STATE_TYPE_BARBARIAN_MALE_DW_HIRLWIND_END,
	STATE_TYPE_BARBARIAN_MALE_DW_HIT,
	STATE_TYPE_BARBARIAN_MALE_DW_IDLE,
	STATE_TYPE_BARBARIAN_MALE_DW_KNOCKBACK_END,
	STATE_TYPE_BARBARIAN_MALE_DW_KNOCKBACK_LOOP,
	STATE_TYPE_BARBARIAN_MALE_DW_LEAPATTACK_AIR,
	STATE_TYPE_BARBARIAN_MALE_DW_LEAPATTACK_END,
	STATE_TYPE_BARBARIAN_MALE_DW_PARRY,
	STATE_TYPE_BARBARIAN_MALE_DW_REVENGE,
	STATE_TYPE_BARBARIAN_MALE_DW_RUN,
	STATE_TYPE_BARBARIAN_MALE_1HS_MEZ,
	STATE_TYPE_BARBARIAN_MALE_1HT_MEZ,
	STATE_TYPE_BARBARIAN_MALE_2HS_MEZ,
	STATE_TYPE_BARBARIAN_MALE_2HT_MEZ,
	STATE_TYPE_BARBARIAN_MALE_STF_MEZ,
	STATE_TYPE_BARBARIAN_MALE_DW_MEZ,




	//Monk
	STATE_TYPE_MONK_MALE_1HS_ATTACK,
	STATE_TYPE_MONK_MALE_1HS_BUFF,
	STATE_TYPE_MONK_MALE_1HS_CELESTIALWHEEL,
	STATE_TYPE_MONK_MALE_1HS_DEBILITATINGBLOWS_01,
	STATE_TYPE_MONK_MALE_1HS_DEBILITATINGBLOWS_02,
	STATE_TYPE_MONK_MALE_1HS_DEBILITATINGBLOWS_03_1,
	STATE_TYPE_MONK_MALE_1HS_DEBILITATINGBLOWS_03_2,
	STATE_TYPE_MONK_MALE_1HS_HIT,
	STATE_TYPE_MONK_MALE_1HS_HOBBLE_RUN,
	STATE_TYPE_MONK_MALE_1HS_IDLE,
	STATE_TYPE_MONK_MALE_1HS_KNOCKBACK,
	STATE_TYPE_MONK_MALE_1HS_KNOCKBACK_END,
	STATE_TYPE_MONK_MALE_1HS_LASHINGTAIL,
	STATE_TYPE_MONK_MALE_1HS_LETGAL_DECOY,
	STATE_TYPE_MONK_MALE_1HS_LIGHTNING_01,
	STATE_TYPE_MONK_MALE_1HS_LIGHTNING_02,
	STATE_TYPE_MONK_MALE_1HS_LIGHTNING_03,
	STATE_TYPE_MONK_MALE_1HS_LONGREACH_01,
	STATE_TYPE_MONK_MALE_1HS_LONGREACH_02,
	STATE_TYPE_MONK_MALE_1HS_LONGREACH_03,
	STATE_TYPE_MONK_MALE_1HS_RAPIDSTRIKES_01,
	STATE_TYPE_MONK_MALE_1HS_RAPIDSTRIKES_02,
	STATE_TYPE_MONK_MALE_1HS_RAPIDSTRIKES_03,
	STATE_TYPE_MONK_MALE_1HS_STUNNED,
	STATE_TYPE_MONK_MALE_1HS_WAVEOFLIGHT,
	STATE_TYPE_MONK_MALE_1HT_ATTACK,
	STATE_TYPE_MONK_MALE_1HT_BUFF,
	STATE_TYPE_MONK_MALE_1HT_CELESTIALWHEEL,
	STATE_TYPE_MONK_MALE_1HT_DEBILITATINGBLOWS_01,
	STATE_TYPE_MONK_MALE_1HT_DEBILITATINGBLOWS_02,
	STATE_TYPE_MONK_MALE_1HT_DEBILITATINGBLOWS_03_1,
	STATE_TYPE_MONK_MALE_1HT_DEBILITATINGBLOWS_03_2,
	STATE_TYPE_MONK_MALE_1HT_HIT,
	STATE_TYPE_MONK_MALE_1HT_HOBBLE_RUN,
	STATE_TYPE_MONK_MALE_1HT_IDLE,
	STATE_TYPE_MONK_MALE_1HT_KNOCKBACK,
	STATE_TYPE_MONK_MALE_1HT_KNOCKBACK_END,
	STATE_TYPE_MONK_MALE_1HT_LASHINGTAIL,
	STATE_TYPE_MONK_MALE_1HT_LETGAL_DECOY,
	STATE_TYPE_MONK_MALE_1HT_LIGHTNING_01,
	STATE_TYPE_MONK_MALE_1HT_LIGHTNING_02,
	STATE_TYPE_MONK_MALE_1HT_LIGHTNING_03,
	STATE_TYPE_MONK_MALE_1HT_LONGREACH_01,
	STATE_TYPE_MONK_MALE_1HT_LONGREACH_02,
	STATE_TYPE_MONK_MALE_1HT_LONGREACH_03,
	STATE_TYPE_MONK_MALE_1HT_RAPIDSTRIKES_01,
	STATE_TYPE_MONK_MALE_1HT_RAPIDSTRIKES_02,
	STATE_TYPE_MONK_MALE_1HT_RAPIDSTRIKES_03,
	STATE_TYPE_MONK_MALE_1HT_STUNNED,
	STATE_TYPE_MONK_MALE_1HT_WAVEOFLIGHT,
	STATE_TYPE_MONK_MALE_2HT_ATTACK,
	STATE_TYPE_MONK_MALE_2HT_BUFF,
	STATE_TYPE_MONK_MALE_2HT_CELESTIALWHEEL,
	STATE_TYPE_MONK_MALE_2HT_DEBILITATINGBLOWS_01,
	STATE_TYPE_MONK_MALE_2HT_DEBILITATINGBLOWS_02,
	STATE_TYPE_MONK_MALE_2HT_DEBILITATINGBLOWS_03_1,
	STATE_TYPE_MONK_MALE_2HT_DEBILITATINGBLOWS_03_2,
	STATE_TYPE_MONK_MALE_2HT_HIT,
	STATE_TYPE_MONK_MALE_2HT_HOBBLE_RUN,
	STATE_TYPE_MONK_MALE_2HT_IDLE,
	STATE_TYPE_MONK_MALE_2HT_KNOCKBACK,
	STATE_TYPE_MONK_MALE_2HT_KNOCKBACK_END,
	STATE_TYPE_MONK_MALE_2HT_LASHINGTAIL,
	STATE_TYPE_MONK_MALE_2HT_LETGAL_DECOY,
	STATE_TYPE_MONK_MALE_2HT_LIGHTNING_01,
	STATE_TYPE_MONK_MALE_2HT_LIGHTNING_02,
	STATE_TYPE_MONK_MALE_2HT_LIGHTNING_03,
	STATE_TYPE_MONK_MALE_2HT_LONGREACH_01,
	STATE_TYPE_MONK_MALE_2HT_LONGREACH_02,
	STATE_TYPE_MONK_MALE_2HT_LONGREACH_03,
	STATE_TYPE_MONK_MALE_2HT_RAPIDSTRIKES_01,
	STATE_TYPE_MONK_MALE_2HT_RAPIDSTRIKES_02,
	STATE_TYPE_MONK_MALE_2HT_RAPIDSTRIKES_03,
	STATE_TYPE_MONK_MALE_2HT_STUNNED,
	STATE_TYPE_MONK_MALE_2HT_WAVEOFLIGHT,
	STATE_TYPE_MONK_MALE_STF_ATTACK,
	STATE_TYPE_MONK_MALE_STF_BUFF,
	STATE_TYPE_MONK_MALE_STF_CELESTIALWHEEL,
	STATE_TYPE_MONK_MALE_STF_DEBILITATINGBLOWS_01,
	STATE_TYPE_MONK_MALE_STF_DEBILITATINGBLOWS_02,
	STATE_TYPE_MONK_MALE_STF_DEBILITATINGBLOWS_03_1,
	STATE_TYPE_MONK_MALE_STF_DEBILITATINGBLOWS_03_2,
	STATE_TYPE_MONK_MALE_STF_HIT,
	STATE_TYPE_MONK_MALE_STF_HOBBLE_RUN,
	STATE_TYPE_MONK_MALE_STF_IDLE,
	STATE_TYPE_MONK_MALE_STF_KNOCKBACK,
	STATE_TYPE_MONK_MALE_STF_KNOCKBACK_END,
	STATE_TYPE_MONK_MALE_STF_LASHINGTAIL,
	STATE_TYPE_MONK_MALE_STF_LETGAL_DECOY,
	STATE_TYPE_MONK_MALE_STF_LIGHTNING_01,
	STATE_TYPE_MONK_MALE_STF_LIGHTNING_02,
	STATE_TYPE_MONK_MALE_STF_LIGHTNING_03,
	STATE_TYPE_MONK_MALE_STF_LONGREACH_01,
	STATE_TYPE_MONK_MALE_STF_LONGREACH_02,
	STATE_TYPE_MONK_MALE_STF_LONGREACH_03,
	STATE_TYPE_MONK_MALE_STF_RAPIDSTRIKES_01,
	STATE_TYPE_MONK_MALE_STF_RAPIDSTRIKES_02,
	STATE_TYPE_MONK_MALE_STF_RAPIDSTRIKES_03,
	STATE_TYPE_MONK_MALE_STF_STUNNED,
	STATE_TYPE_MONK_MALE_STF_WAVEOFLIGHT,
	STATE_TYPE_MONK_MALE_DW_FF_ATTACK_R,
	STATE_TYPE_MONK_MALE_DW_FF_ATTACK_L,
	STATE_TYPE_MONK_MALE_DW_FF_BUFF,
	STATE_TYPE_MONK_MALE_DW_FF_CELESTIALWHEEL,
	STATE_TYPE_MONK_MALE_DW_FF_DEBILITATINGBLOWS_01,
	STATE_TYPE_MONK_MALE_DW_FF_DEBILITATINGBLOWS_02,
	STATE_TYPE_MONK_MALE_DW_FF_DEBILITATINGBLOWS_03_1,
	STATE_TYPE_MONK_MALE_DW_FF_DEBILITATINGBLOWS_03_2,
	STATE_TYPE_MONK_MALE_DW_FF_HIT,
	STATE_TYPE_MONK_MALE_DW_FF_HOBBLE_RUN,
	STATE_TYPE_MONK_MALE_DW_FF_IDLE,
	STATE_TYPE_MONK_MALE_DW_FF_KNOCKBACK,
	STATE_TYPE_MONK_MALE_DW_FF_KNOCKBACK_END,
	STATE_TYPE_MONK_MALE_DW_FF_LASHINGTAIL,
	STATE_TYPE_MONK_MALE_DW_FF_LETGAL_DECOY,
	STATE_TYPE_MONK_MALE_DW_FF_LIGHTNING_01,
	STATE_TYPE_MONK_MALE_DW_FF_LIGHTNING_02,
	STATE_TYPE_MONK_MALE_DW_FF_LIGHTNING_03,
	STATE_TYPE_MONK_MALE_DW_FF_LONGREACH_01,
	STATE_TYPE_MONK_MALE_DW_FF_LONGREACH_02,
	STATE_TYPE_MONK_MALE_DW_FF_LONGREACH_03,
	STATE_TYPE_MONK_MALE_DW_FF_RAPIDSTRIKES_01,
	STATE_TYPE_MONK_MALE_DW_FF_RAPIDSTRIKES_02,
	STATE_TYPE_MONK_MALE_DW_FF_RAPIDSTRIKES_03,
	STATE_TYPE_MONK_MALE_DW_FF_STUNNED,
	STATE_TYPE_MONK_MALE_DW_FF_WAVEOFLIGHT,
	STATE_TYPE_MONK_MALE_DW_SF_ATTACK_R,
	STATE_TYPE_MONK_MALE_DW_SF_ATTACK_L,
	STATE_TYPE_MONK_MALE_DW_SF_BUFF,
	STATE_TYPE_MONK_MALE_DW_SF_CELESTIALWHEEL,
	STATE_TYPE_MONK_MALE_DW_SF_DEBILITATINGBLOWS_01,
	STATE_TYPE_MONK_MALE_DW_SF_DEBILITATINGBLOWS_02,
	STATE_TYPE_MONK_MALE_DW_SF_DEBILITATINGBLOWS_03_1,
	STATE_TYPE_MONK_MALE_DW_SF_DEBILITATINGBLOWS_03_2,
	STATE_TYPE_MONK_MALE_DW_SF_HIT,
	STATE_TYPE_MONK_MALE_DW_SF_HOBBLE_RUN,
	STATE_TYPE_MONK_MALE_DW_SF_IDLE,
	STATE_TYPE_MONK_MALE_DW_SF_KNOCKBACK,
	STATE_TYPE_MONK_MALE_DW_SF_KNOCKBACK_END,
	STATE_TYPE_MONK_MALE_DW_SF_LASHINGTAIL,
	STATE_TYPE_MONK_MALE_DW_SF_LETGAL_DECOY,
	STATE_TYPE_MONK_MALE_DW_SF_LIGHTNING_01,
	STATE_TYPE_MONK_MALE_DW_SF_LIGHTNING_02,
	STATE_TYPE_MONK_MALE_DW_SF_LIGHTNING_03,
	STATE_TYPE_MONK_MALE_DW_SF_LONGREACH_01,
	STATE_TYPE_MONK_MALE_DW_SF_LONGREACH_02,
	STATE_TYPE_MONK_MALE_DW_SF_LONGREACH_03,
	STATE_TYPE_MONK_MALE_DW_SF_RAPIDSTRIKES_01,
	STATE_TYPE_MONK_MALE_DW_SF_RAPIDSTRIKES_02,
	STATE_TYPE_MONK_MALE_DW_SF_RAPIDSTRIKES_03,
	STATE_TYPE_MONK_MALE_DW_SF_STUNNED,
	STATE_TYPE_MONK_MALE_DW_SF_WAVEOFLIGHT,
	STATE_TYPE_MONK_MALE_DW_SS_ATTACK_R,
	STATE_TYPE_MONK_MALE_DW_SS_ATTACK_L,
	STATE_TYPE_MONK_MALE_DW_SS_BUFF,
	STATE_TYPE_MONK_MALE_DW_SS_CELESTIALWHEEL,
	STATE_TYPE_MONK_MALE_DW_SS_DEBILITATINGBLOWS_01,
	STATE_TYPE_MONK_MALE_DW_SS_DEBILITATINGBLOWS_02,
	STATE_TYPE_MONK_MALE_DW_SS_DEBILITATINGBLOWS_03_1,
	STATE_TYPE_MONK_MALE_DW_SS_DEBILITATINGBLOWS_03_2,
	STATE_TYPE_MONK_MALE_DW_SS_HIT,
	STATE_TYPE_MONK_MALE_DW_SS_HOBBLE_RUN,
	STATE_TYPE_MONK_MALE_DW_SS_IDLE,
	STATE_TYPE_MONK_MALE_DW_SS_KNOCKBACK,
	STATE_TYPE_MONK_MALE_DW_SS_KNOCKBACK_END,
	STATE_TYPE_MONK_MALE_DW_SS_LASHINGTAIL,
	STATE_TYPE_MONK_MALE_DW_SS_LETGAL_DECOY,
	STATE_TYPE_MONK_MALE_DW_SS_LIGHTNING_01,
	STATE_TYPE_MONK_MALE_DW_SS_LIGHTNING_02,
	STATE_TYPE_MONK_MALE_DW_SS_LIGHTNING_03,
	STATE_TYPE_MONK_MALE_DW_SS_LONGREACH_01,
	STATE_TYPE_MONK_MALE_DW_SS_LONGREACH_02,
	STATE_TYPE_MONK_MALE_DW_SS_LONGREACH_03,
	STATE_TYPE_MONK_MALE_DW_SS_RAPIDSTRIKES_01,
	STATE_TYPE_MONK_MALE_DW_SS_RAPIDSTRIKES_02,
	STATE_TYPE_MONK_MALE_DW_SS_RAPIDSTRIKES_03,
	STATE_TYPE_MONK_MALE_DW_SS_STUNNED,
	STATE_TYPE_MONK_MALE_DW_SS_WAVEOFLIGHT,
	STATE_TYPE_MONK_MALE_1HS_DASHINGSTRIKE,
	STATE_TYPE_MONK_MALE_1HT_DASHINGSTRIKE,
	STATE_TYPE_MONK_MALE_2HT_DASHINGSTRIKE,
	STATE_TYPE_MONK_MALE_STF_DASHINGSTRIKE,
	STATE_TYPE_MONK_MALE_DW_FF_DASHINGSTRIKE,
	STATE_TYPE_MONK_MALE_DW_SF_DASHINGSTRIKE,
	STATE_TYPE_MONK_MALE_DW_SS_DASHINGSTRIKE,
	STATE_TYPE_MONK_MALE_1HS_RUN,
	STATE_TYPE_MONK_MALE_1HT_RUN,
	STATE_TYPE_MONK_MALE_2HT_RUN,
	STATE_TYPE_MONK_MALE_STF_RUN,
	STATE_TYPE_MONK_MALE_DW_FF_RUN,
	STATE_TYPE_MONK_MALE_DW_SF_RUN,
	STATE_TYPE_MONK_MALE_DW_SS_RUN,
	STATE_TYPE_MONK_MALE_1HS_MEZ,
	STATE_TYPE_MONK_MALE_1HT_MEZ,
	STATE_TYPE_MONK_MALE_2HT_MEZ,
	STATE_TYPE_MONK_MALE_STF_MEZ,
	STATE_TYPE_MONK_MALE_DW_FF_MEZ,
	STATE_TYPE_MONK_MALE_DW_SF_MEZ,
	STATE_TYPE_MONK_MALE_DW_SS_MEZ,

	//WitchDoctor
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_ACIDCLOUD_BARF,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_FASTCAST,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_FIREBALL,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_HORRIFY,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_SOUL_HARVEST,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_BLOW,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_CHANNEL,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_FLAYERARMY,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_SUMMON,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_SUMMON_CHARGER,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_ATTACK,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_HIT,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_KNOCKBACK,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_KNOCKBACK_END,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_STUNNED,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_RUN,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_IDLE,
	STATE_TYPE_WITCHDOCTOR_MALE_XBOW_MEZ,
	STATE_TYPE_WITCHDOCTOR_MALE_BOW_MEZ,
	STATE_TYPE_WITCHDOCTOR_MALE_STF_MEZ,
	STATE_TYPE_WITCHDOCTOR_MALE_1HT_MEZ,
	STATE_TYPE_WITCHDOCTOR_MALE_1HS_MEZ,
	STATE_TYPE_WITCHDOCTOR_MALE_2HT_MEZ,
	STATE_TYPE_WITCHDOCTOR_MALE_2HS_MEZ,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HS_MEZ,
	STATE_TYPE_WITCHDOCTOR_MALE_MOJO_1HT_MEZ,
	

	// Butcher
	STATE_TYPE_BUTCHER_ATTACK1,
	STATE_TYPE_BUTCHER_ATTACK2,
	STATE_TYPE_BUTCHER_CHAIN_IN,
	STATE_TYPE_BUTCHER_CHAIN_OUT,
	STATE_TYPE_BUTCHER_CHARGE_IN,
	STATE_TYPE_BUTCHER_DEATH,
	STATE_TYPE_BUTCHER_FAN_OF_CHAINS,
	STATE_TYPE_BUTCHER_IDLE,
	STATE_TYPE_BUTCHER_INTRO,
	STATE_TYPE_BUTCHER_INTRO_WALK,
	STATE_TYPE_BUTCHER_PHASE_CHANGE,
	STATE_TYPE_BUTCHER_PULL_ATTACK,
	STATE_TYPE_BUTCHER_RUN,
	STATE_TYPE_BUTCHER_STUNNED,
	STATE_TYPE_BUTCHER_WALK,

	// Ghoul
	STATE_TYPE_GHOUL_ATTACK1,
	STATE_TYPE_GHOUL_ATTACK2,
	STATE_TYPE_GHOUL_DEATH,
	STATE_TYPE_GHOUL_HIT,
	STATE_TYPE_GHOUL_IDLE,
	STATE_TYPE_GHOUL_RUN,

	// Skeleton_Archer_Brown
	STATE_TYPE_SKELETON_ARCHER_BROWN_ATTACK,
	STATE_TYPE_SKELETON_ARCHER_BROWN_DEATH,
	STATE_TYPE_SKELETON_ARCHER_BROWN_HIT,
	STATE_TYPE_SKELETON_ARCHER_BROWN_IDLE,
	STATE_TYPE_SKELETON_ARCHER_BROWN_RUN,
	STATE_TYPE_SKELETON_ARCHER_BROWN_SPAWN,
	STATE_TYPE_SKELETON_ARCHER_BROWN_WALK,

	// Skeleton_Archer_Mint
	STATE_TYPE_SKELETON_ARCHER_MINT_ATTACK,
	STATE_TYPE_SKELETON_ARCHER_MINT_DEATH,
	STATE_TYPE_SKELETON_ARCHER_MINT_HIT,
	STATE_TYPE_SKELETON_ARCHER_MINT_IDLE,
	STATE_TYPE_SKELETON_ARCHER_MINT_RUN,
	STATE_TYPE_SKELETON_ARCHER_MINT_SPAWN,
	STATE_TYPE_SKELETON_ARCHER_MINT_WALK,

	// Skeleton_Archer_Red
	STATE_TYPE_SKELETON_ARCHER_RED_ATTACK,
	STATE_TYPE_SKELETON_ARCHER_RED_DEATH,
	STATE_TYPE_SKELETON_ARCHER_RED_HIT,
	STATE_TYPE_SKELETON_ARCHER_RED_IDLE,
	STATE_TYPE_SKELETON_ARCHER_RED_RUN,
	STATE_TYPE_SKELETON_ARCHER_RED_SPAWN,
	STATE_TYPE_SKELETON_ARCHER_RED_WALK,

	// Skeleton_Axe_Blue
	STATE_TYPE_SKELETON_AXE_BLUE_ATTACK1,
	STATE_TYPE_SKELETON_AXE_BLUE_ATTACK2,
	STATE_TYPE_SKELETON_AXE_BLUE_DEATH,
	STATE_TYPE_SKELETON_AXE_BLUE_HIT,
	STATE_TYPE_SKELETON_AXE_BLUE_IDLE,
	STATE_TYPE_SKELETON_AXE_BLUE_RUN,
	STATE_TYPE_SKELETON_AXE_BLUE_SPAWN,

	// Skeleton_Axe_Red
	STATE_TYPE_SKELETON_AXE_RED_ATTACK1,
	STATE_TYPE_SKELETON_AXE_RED_ATTACK2,
	STATE_TYPE_SKELETON_AXE_RED_DEATH,
	STATE_TYPE_SKELETON_AXE_RED_HIT,
	STATE_TYPE_SKELETON_AXE_RED_IDLE,
	STATE_TYPE_SKELETON_AXE_RED_RUN,
	STATE_TYPE_SKELETON_AXE_RED_SPAWN,

	// Skeleton_King
	STATE_TYPE_SKELETON_KING_ATTACK1,
	STATE_TYPE_SKELETON_KING_DEATH,
	STATE_TYPE_SKELETON_KING_IDLE,
	STATE_TYPE_SKELETON_KING_INTRO,
	STATE_TYPE_SKELETON_KING_INTRO_IDLE,
	STATE_TYPE_SKELETON_KING_SUMMON,
	STATE_TYPE_SKELETON_KING_TAUNT,
	STATE_TYPE_SKELETON_KING_TELEPORT,
	STATE_TYPE_SKELETON_KING_TELEPORT_ATTACK,
	STATE_TYPE_SKELETON_KING_TELEPORT_BACK,
	STATE_TYPE_SKELETON_KING_TELEPORT_BACK_POSE,
	STATE_TYPE_SKELETON_KING_TELEPORT_POSE,
	STATE_TYPE_SKELETON_KING_WALK,
	STATE_TYPE_SKELETON_KING_WHIRLWIND_END,
	STATE_TYPE_SKELETON_KING_WHIRLWIND_LOOP,
	STATE_TYPE_SKELETON_KING_WHIRLWIND_START,

	// Skeleton_OneHand_Blue
	STATE_TYPE_SKELETON_ONEHAND_BLUE_ATTACK,
	STATE_TYPE_SKELETON_ONEHAND_BLUE_DEATH,
	STATE_TYPE_SKELETON_ONEHAND_BLUE_HIT,
	STATE_TYPE_SKELETON_ONEHAND_BLUE_IDLE,
	STATE_TYPE_SKELETON_ONEHAND_BLUE_RUN,
	STATE_TYPE_SKELETON_ONEHAND_BLUE_SPAWN,

	// Skeleton_OneHand_Brown
	STATE_TYPE_SKELETON_ONEHAND_BROWN_ATTACK,
	STATE_TYPE_SKELETON_ONEHAND_BROWN_DEATH,
	STATE_TYPE_SKELETON_ONEHAND_BROWN_HIT,
	STATE_TYPE_SKELETON_ONEHAND_BROWN_IDLE,
	STATE_TYPE_SKELETON_ONEHAND_BROWN_RUN,
	STATE_TYPE_SKELETON_ONEHAND_BROWN_SPAWN,

	// Skeleton_OneHand_Mint
	STATE_TYPE_SKELETON_ONEHAND_MINT_ATTACK,
	STATE_TYPE_SKELETON_ONEHAND_MINT_DEATH,
	STATE_TYPE_SKELETON_ONEHAND_MINT_HIT,
	STATE_TYPE_SKELETON_ONEHAND_MINT_IDLE,
	STATE_TYPE_SKELETON_ONEHAND_MINT_RUN,
	STATE_TYPE_SKELETON_ONEHAND_MINT_SPAWN,

	// Skeleton_Shield_Blue
	STATE_TYPE_SKELETON_SHIELD_BLUE_ATTACK,
	STATE_TYPE_SKELETON_SHIELD_BLUE_DEATH,
	STATE_TYPE_SKELETON_SHIELD_BLUE_HIT,
	STATE_TYPE_SKELETON_SHIELD_BLUE_IDLE,
	STATE_TYPE_SKELETON_SHIELD_BLUE_WALK,
	STATE_TYPE_SKELETON_SHIELD_BLUE_SPAWN,

	// Skeleton_Shield_Brown
	STATE_TYPE_SKELETON_SHIELD_BROWN_ATTACK,
	STATE_TYPE_SKELETON_SHIELD_BROWN_DEATH,
	STATE_TYPE_SKELETON_SHIELD_BROWN_HIT,
	STATE_TYPE_SKELETON_SHIELD_BROWN_IDLE,
	STATE_TYPE_SKELETON_SHIELD_BROWN_WALK,
	STATE_TYPE_SKELETON_SHIELD_BROWN_SPAWN,

	// Skeleton_Shield_Mint
	STATE_TYPE_SKELETON_SHIELD_MINT_ATTACK,
	STATE_TYPE_SKELETON_SHIELD_MINT_DEATH,
	STATE_TYPE_SKELETON_SHIELD_MINT_HIT,
	STATE_TYPE_SKELETON_SHIELD_MINT_IDLE,
	STATE_TYPE_SKELETON_SHIELD_MINT_WALK,
	STATE_TYPE_SKELETON_SHIELD_MINT_SPAWN,

	// Skeleton_Shield_Red
	STATE_TYPE_SKELETON_SHIELD_RED_ATTACK,
	STATE_TYPE_SKELETON_SHIELD_RED_DEATH,
	STATE_TYPE_SKELETON_SHIELD_RED_HIT,
	STATE_TYPE_SKELETON_SHIELD_RED_IDLE,
	STATE_TYPE_SKELETON_SHIELD_RED_WALK,
	STATE_TYPE_SKELETON_SHIELD_RED_SPAWN,

	// Skeleton_Summoner_Blue
	STATE_TYPE_SKELETON_SUMMONER_BLUE_DEATH,
	STATE_TYPE_SKELETON_SUMMONER_BLUE_HIT,
	STATE_TYPE_SKELETON_SUMMONER_BLUE_IDLE,
	STATE_TYPE_SKELETON_SUMMONER_BLUE_MAGIC,
	STATE_TYPE_SKELETON_SUMMONER_BLUE_SUMMON,
	STATE_TYPE_SKELETON_SUMMONER_BLUE_WALK,

	// Skeleton_Summoner_Brown
	STATE_TYPE_SKELETON_SUMMONER_BROWN_DEATH,
	STATE_TYPE_SKELETON_SUMMONER_BROWN_HIT,
	STATE_TYPE_SKELETON_SUMMONER_BROWN_IDLE,
	STATE_TYPE_SKELETON_SUMMONER_BROWN_MAGIC,
	STATE_TYPE_SKELETON_SUMMONER_BROWN_SUMMON,
	STATE_TYPE_SKELETON_SUMMONER_BROWN_WALK,

	// Skeleton_Summoner_Red
	STATE_TYPE_SKELETON_SUMMONER_RED_DEATH,
	STATE_TYPE_SKELETON_SUMMONER_RED_HIT,
	STATE_TYPE_SKELETON_SUMMONER_RED_IDLE,
	STATE_TYPE_SKELETON_SUMMONER_RED_MAGIC,
	STATE_TYPE_SKELETON_SUMMONER_RED_SUMMON,
	STATE_TYPE_SKELETON_SUMMONER_RED_WALK,

	// Stitch
	STATE_TYPE_STITCH_ATTACK,
	STATE_TYPE_STITCH_ATTACK2,
	STATE_TYPE_STITCH_ATTACK3,
	STATE_TYPE_STITCH_DEATH,
	STATE_TYPE_STITCH_HIT,
	STATE_TYPE_STITCH_IDLE,
	STATE_TYPE_STITCH_RUN,
	STATE_TYPE_STITCH_WALK,

	// Triune_Berserker
	STATE_TYPE_TRIUNE_BERSERKER_ATTACK1,
	STATE_TYPE_TRIUNE_BERSERKER_ATTACK2,
	STATE_TYPE_TRIUNE_BERSERKER_DEATH,
	STATE_TYPE_TRIUNE_BERSERKER_HIT,
	STATE_TYPE_TRIUNE_BERSERKER_IDLE,
	STATE_TYPE_TRIUNE_BERSERKER_RUN,

	// Triune_Cultists
	STATE_TYPE_TRIUNE_CULTISTS_ATTACK,
	STATE_TYPE_TRIUNE_CULTISTS_DEATH,
	STATE_TYPE_TRIUNE_CULTISTS_HIT,
	STATE_TYPE_TRIUNE_CULTISTS_IDLE,
	STATE_TYPE_TRIUNE_CULTISTS_RUN,
	STATE_TYPE_TRIUNE_CULTISTS_WALK,

	// Triune_Possessed
	STATE_TYPE_TRIUNE_POSSESSED_ACTIVATION,
	STATE_TYPE_TRIUNE_POSSESSED_ATTACK1,
	STATE_TYPE_TRIUNE_POSSESSED_ATTACK2_MIDDLE,
	STATE_TYPE_TRIUNE_POSSESSED_ATTACK2_END,
	STATE_TYPE_TRIUNE_POSSESSED_DEATH,
	STATE_TYPE_TRIUNE_POSSESSED_HIT,
	STATE_TYPE_TRIUNE_POSSESSED_IDLE,
	STATE_TYPE_TRIUNE_POSSESSED_WALK,

	// Triune_Vessel
	STATE_TYPE_TRIUNE_VESSEL_ACTIVATING,
	STATE_TYPE_TRIUNE_VESSEL_ACTIVATION,
	STATE_TYPE_TRIUNE_VESSEL_DEATH,
	STATE_TYPE_TRIUNE_VESSEL_HIT,
	STATE_TYPE_TRIUNE_VESSEL_IDLE,
	STATE_TYPE_TRIUNE_VESSEL_WALK,

	// Warden
	STATE_TYPE_WARDEN_ATTACK1,
	STATE_TYPE_WARDEN_ATTACK2,
	STATE_TYPE_WARDEN_DEATH,
	STATE_TYPE_WARDEN_HIT,
	STATE_TYPE_WARDEN_IDLE,
	STATE_TYPE_WARDEN_RUN,

	// Zombie_Female
	STATE_TYPE_ZOMBIE_FEMALE_ATTACK,
	STATE_TYPE_ZOMBIE_FEMALE_ATTACK2,
	STATE_TYPE_ZOMBIE_FEMALE_ATTACK3,
	STATE_TYPE_ZOMBIE_FEMALE_ATTACK4,
	STATE_TYPE_ZOMBIE_FEMALE_DEATH,
	STATE_TYPE_ZOMBIE_FEMALE_HIT,
	STATE_TYPE_ZOMBIE_FEMALE_IDLE,
	STATE_TYPE_ZOMBIE_FEMALE_WALK,

	// Zombie_Male
	STATE_TYPE_ZOMBIE_MALE_ATTACK,
	STATE_TYPE_ZOMBIE_MALE_DEATH,
	STATE_TYPE_ZOMBIE_MALE_HIT,
	STATE_TYPE_ZOMBIE_MALE_IDLE,
	STATE_TYPE_ZOMBIE_MALE_WALK,

	// Zombie_Skinny_Male_White
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_ATTACK1,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_ATTACK2,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_ATTACK3,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_ATTACK4,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_DEATH,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_HIT,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_IDLE,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_SPAWN,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_WHITE_WALK1,

	// Zombie_Skinny_Male_Red
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_ATTACK1,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_ATTACK2,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_ATTACK3,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_ATTACK4,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_DEATH,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_HIT,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_IDLE,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_SPAWN,
	STATE_TYPE_ZOMBIE_SKINNY_MALE_RED_WALK1,

	// ENCHANTRESS
	STATE_TYPE_ENCHANTRESS_1HS_AMPLIFY_DAMAGE_01,
	STATE_TYPE_ENCHANTRESS_1HS_AOE_01,
	STATE_TYPE_ENCHANTRESS_1HS_AOE_02,
	STATE_TYPE_ENCHANTRESS_1HS_AOE_02_NOYELL,
	STATE_TYPE_ENCHANTRESS_1HS_BUFF_01,
	STATE_TYPE_ENCHANTRESS_1HS_CAST_01,
	STATE_TYPE_ENCHANTRESS_1HS_EMOTE_GREET_01,
	STATE_TYPE_ENCHANTRESS_1HS_ENERGIZE_01,
	STATE_TYPE_ENCHANTRESS_1HS_ENERGY_BOMB_01,
	STATE_TYPE_ENCHANTRESS_1HS_FORCEFUL_PUSH_01,
	STATE_TYPE_ENCHANTRESS_1HS_GET_HIT_01,
	STATE_TYPE_ENCHANTRESS_1HS_IDLE_01,
	STATE_TYPE_ENCHANTRESS_1HS_KNOCKBACK_LAND_01,
	STATE_TYPE_ENCHANTRESS_1HS_KNOCKBACK_LOOP_01,
	STATE_TYPE_ENCHANTRESS_1HS_LOWERED_RESISTANCE_01,
	STATE_TYPE_ENCHANTRESS_1HS_MELEE_01,
	STATE_TYPE_ENCHANTRESS_1HS_PARRY_01,
	STATE_TYPE_ENCHANTRESS_1HS_REFELECT_MISSLE_01,
	STATE_TYPE_ENCHANTRESS_1HS_RESURRECTION_INTRO_01,
	STATE_TYPE_ENCHANTRESS_1HS_RESURRECTION_LOOP_01,
	STATE_TYPE_ENCHANTRESS_1HS_RESURRECTION_OUTRO_01,
	STATE_TYPE_ENCHANTRESS_1HS_RUN_01,
	STATE_TYPE_ENCHANTRESS_1HS_STUNNED_01,
	STATE_TYPE_ENCHANTRESS_1HS_WALK_01,
	STATE_TYPE_ENCHANTRESS_AMPLIFY_DAMAGE_01,
	STATE_TYPE_ENCHANTRESS_AOE_01,
	STATE_TYPE_ENCHANTRESS_AOE_02,
	STATE_TYPE_ENCHANTRESS_BUFF_01,
	STATE_TYPE_ENCHANTRESS_CAST_01,
	STATE_TYPE_ENCHANTRESS_EMOTE_GREET_01,
	STATE_TYPE_ENCHANTRESS_ENERGIZE_01,
	STATE_TYPE_ENCHANTRESS_ENERGY_BOMB_01,
	STATE_TYPE_ENCHANTRESS_FORCEFUL_PUSH_01,
	STATE_TYPE_ENCHANTRESS_GET_HIT_01,
	STATE_TYPE_ENCHANTRESS_HTH_AMPLIFY_DAMAGE_01,
	STATE_TYPE_ENCHANTRESS_HTH_AOE_01,
	STATE_TYPE_ENCHANTRESS_HTH_AOE_02,
	STATE_TYPE_ENCHANTRESS_HTH_BUFF_01,
	STATE_TYPE_ENCHANTRESS_HTH_CAST_01,
	STATE_TYPE_ENCHANTRESS_HTH_ENERGIZE_01,
	STATE_TYPE_ENCHANTRESS_HTH_ENERGY_BOMB_01,
	STATE_TYPE_ENCHANTRESS_HTH_FORCEFUL_PUSH_01,
	STATE_TYPE_ENCHANTRESS_HTH_IDLE_01,
	STATE_TYPE_ENCHANTRESS_HTH_KNOCKBACK_LAND_01,
	STATE_TYPE_ENCHANTRESS_HTH_KNOCKBACK_LOOP_01,
	STATE_TYPE_ENCHANTRESS_HTH_LOWERED_RESISTANCE_01,
	STATE_TYPE_ENCHANTRESS_HTH_MELEE_01,
	STATE_TYPE_ENCHANTRESS_HTH_PARRY_01,
	STATE_TYPE_ENCHANTRESS_HTH_REFLECT_MISSILE_01,
	STATE_TYPE_ENCHANTRESS_HTH_RESURRECTION_INTRO_01,
	STATE_TYPE_ENCHANTRESS_HTH_RESURRECTION_LOOP_01,
	STATE_TYPE_ENCHANTRESS_HTH_RESURRECTION_OUTRO_01,
	STATE_TYPE_ENCHANTRESS_HTH_RUN_01,
	STATE_TYPE_ENCHANTRESS_HTH_STUNNED_01,
	STATE_TYPE_ENCHANTRESS_HTH_TOWN_IDLE_01,
	STATE_TYPE_ENCHANTRESS_HTH_TOWN_RUN_01,
	STATE_TYPE_ENCHANTRESS_HTH_WALK_01,
	STATE_TYPE_ENCHANTRESS_IDLE_01,
	STATE_TYPE_ENCHANTRESS_KNOCKBACK_01,
	STATE_TYPE_ENCHANTRESS_KNOCKBACK_LOOP_01,
	STATE_TYPE_ENCHANTRESS_LOWERED_RESISTANCE_01,
	STATE_TYPE_ENCHANTRESS_MELEE_01,
	STATE_TYPE_ENCHANTRESS_REFLECT_MISSILE_01,
	STATE_TYPE_ENCHANTRESS_RESURRECTION_INTRO_01,
	STATE_TYPE_ENCHANTRESS_RESURRECTION_LOOP_01,
	STATE_TYPE_ENCHANTRESS_RESURRECTION_OUTRO_01,
	STATE_TYPE_ENCHANTRESS_RUN_01,
	STATE_TYPE_ENCHANTRESS_STF_ENCHANTRESS_PARRY_01,
	STATE_TYPE_ENCHANTRESS_STUNNED_01,
	STATE_TYPE_ENCHANTRESS_WALK_01,
	STATE_TYPE_ENCHANTRESS_WAND_CAST_01,

	// TRISTRAM_BLACKSMITH
	STATE_TYPE_TRISTRAM_BLACKSMITH_IDLE,
	STATE_TYPE_TRISTRAM_BLACKSMITH_CREATE,

	// TRISTRAM_MYSTIC
	STATE_TYPE_TRISTRAM_MYSTIC_IDLE,
	STATE_TYPE_TRISTRAM_MYSTIC_TALK,
	STATE_TYPE_TRISTRAM_MYSTIC_WALK,

	// TRISTRAM_ARGHUS
	STATE_TYPE_TRISTRAM_ARGHUS_IDLE,

	// TRISTRAM_GUARD
	STATE_TYPE_TRISTRAM_GUARD_IDLE,

	// TRISTRAM_JEWELER
	STATE_TYPE_TRISTRAM_JEWELER_IDLE,
	STATE_TYPE_TRISTRAM_JEWELER_TALK,

	// TRISTRAM_TASHUN
	STATE_TYPE_TRISTRAM_TASHUN_IDLE,

	STATE_TYPE_END
};

enum BUFF_TYPE
{
	BUFF_TYPE_SHADOW_POWER,
	BUFF_TYPE_SMOKE_SCREEN,
	BUFF_TYPE_DIAMOND_SKIN,
	BUFF_TYPE_WIZARD_ARMOR,
	BUFF_TYPE_BATTLE_RAGE,
	BUFF_TYPE_SPRINT,
	BUFF_TYPE_WRATH_OF_BERSERKER,
	BUFF_TYPE_MONK_MANTRA,
	BUFF_TYPE_MONK_SERENITY,
	BUFF_TYPE_WITCHDOCTOR_SPIRITWALK,

	BUFF_TYPE_END
};

enum LOAD_TYPE
{
	LOAD_TYPE_BASE,
	LOAD_TYPE_TITLE_SCENE,
	LOAD_TYPE_LOBBY_SCENE,
	LOAD_TYPE_PLAY_SCENE,
	LOAD_TYPE_BARBARIAN_MALE,
	LOAD_TYPE_DEMONHUNTER_MALE,
	LOAD_TYPE_MONK_MALE,
	LOAD_TYPE_WITCHDOCTOR_MALE,
	LOAD_TYPE_WIZARD_MALE,
	LOAD_TYPE_BARBARIAN_FEMALE,
	LOAD_TYPE_DEMONHUNTER_FEMALE,
	LOAD_TYPE_MONK_FEMALE,
	LOAD_TYPE_WITCHDOCTOR_FEMALE,
	LOAD_TYPE_WIZARD_FEMALE,
	LOAD_TYPE_END
};

enum UNLOAD_TYPE
{
	UNLOAD_TYPE_BASE,
	UNLOAD_TYPE_TITLE_SCENE,
	UNLOAD_TYPE_LOBBY_SCENE,
	UNLOAD_TYPE_PLAY_SCENE,
	UNLOAD_TYPE_BARBARIAN_MALE,
	UNLOAD_TYPE_DEMONHUNTER_MALE,
	UNLOAD_TYPE_MONK_MALE,
	UNLOAD_TYPE_WITCHDOCTOR_MALE,
	UNLOAD_TYPE_WIZARD_MALE,
	UNLOAD_TYPE_BARBARIAN_FEMALE,
	UNLOAD_TYPE_DEMONHUNTER_FEMALE,
	UNLOAD_TYPE_MONK_FEMALE,
	UNLOAD_TYPE_WITCHDOCTOR_FEMALE,
	UNLOAD_TYPE_WIZARD_FEMALE,
	UNLOAD_TYPE_END
};

enum NPC_TYPE
{
	NPC_TYPE_TRISTRAM_ARGHUS,
	NPC_TYPE_TRISTRAM_BLACKSMITH,
	NPC_TYPE_TRISTRAM_GUARD,
	NPC_TYPE_TRISTRAM_JEWELER,
	NPC_TYPE_TRISTRAM_MYSTIC,
	NPC_TYPE_TRISTRAM_TASHUN,
	NPC_TYPE_ENCHANTRESS,
	NPC_TYPE_END
};

enum QUEST_TYPE
{
	QUEST_TYPE_MAIN,
	QUEST_TYPE_END
};

enum CASCADED_TYPE
{
	CASCADED_NEAR,
	CASCADED_MIDDLE,
	CASCADED_FAR,
	CASCADED_END
};

enum ACHIEVE_TYPE
{
	ACHIEVE_TYPE_MAIN_QUEST1,
	ACHIEVE_TYPE_MAIN_QUEST2,
	ACHIEVE_TYPE_MAIN_QUEST3,
	ACHIEVE_TYPE_MAIN_QUEST4,
	ACHIEVE_TYPE_MAIN_QUEST5,
	ACHIEVE_TYPE_MAIN_QUEST6,
	ACHIEVE_TYPE_MAIN_QUEST7,
	ACHIEVE_TYPE_MAIN_QUEST8,
	ACHIEVE_TYPE_MAIN_QUEST9,
	ACHIEVE_TYPE_MAIN_QUEST10,
	ACHIEVE_TYPE_MAIN_QUEST11,
	ACHIEVE_TYPE_END
};

enum PROB_TYPE
{
	PROB_TYPE_TRISTRAM_BLACKSMITH_STORE,
	PROB_TYPE_TRISTRAM_BROKEN_FURNITURE,
	PROB_TYPE_TRISTRAM_CAMPFIRE,
	PROB_TYPE_TRISTRAM_GATE_TOWN,
	PROB_TYPE_TRISTRAM_STASH,
	PROB_TYPE_TRISTRAM_WAGON_DESTROYED,
	PROB_TYPE_TRISTRAM_TO_CATH1F_DOOR,
	PROB_TYPE_CATH1F_TO_TRISTRAM_DOOR,
	PROB_TYPE_CATH1F_TO_CATH2F_DOOR,
	PROB_TYPE_CATH2F_TO_CATH1F_DOOR,
	PROB_TYPE_CATH2F_TO_CATH3F_DOOR,
	PROB_TYPE_CATH3F_TO_CATH2F_DOOR,
	PROB_TYPE_CATH3F_TO_CATH4F_DOOR,
	PROB_TYPE_CATH4F_TO_CATH3F_DOOR,
	PROB_TYPE_CATH4F_TO_ROYAL_CHAMBER,
	PROB_TYPE_ROYAL_CHAMBER_TO_CATH4F,
	PROB_TYPE_ROYAL_CHAMBER_TO_REORIK_MANSION,
	PROB_TYPE_CATHEDRAL_DEATH_GAURD,
	PROB_TYPE_GATE,
	PROB_TYPE_GATE_WAY,
	PROB_TYPE_END
};

enum ATTR_TYPE
{
	ATTR_TYPE_PHYSICAL,
	ATTR_TYPE_COLD,
	ATTR_TYPE_FLAME,
	ATTR_TYPE_LIGHTNING,
	ATTR_TYPE_POISON,
	ATTR_TYPE_HOLY,
	ATTR_TYPE_END
};

enum SKILL_TYPE
{
	SKILL_TYPE_ENTANGLE,
	SKILL_TYPE_FULL,
	SKILL_TYPE_PUSH,
	SKILL_TYPE_STUN,
	SKILL_TYPE_END
};

enum MOUSE_OVER_TYPE
{
	MOUSE_OVER_TYPE_NONE = -1,
	MOUSE_OVER_TYPE_NPC,
	MOUSE_OVER_TYPE_DROP_ITEM,
	MOUSE_OVER_TYPE_STATIC_PROB,
	MOUSE_OVER_TYPE_DYNAMIC_PROB,
	MOUSE_OVER_TYPE_MONSTER,
	MOUSE_OVER_TYPE_END
};

enum SLOT_PUSH_TYPE
{
	SLOT_PUSH_TYPE_NONE = -1,
	SLOT_PUSH_TYPE_KEY_1,
	SLOT_PUSH_TYPE_KEY_2,
	SLOT_PUSH_TYPE_KEY_3,
	SLOT_PUSH_TYPE_KEY_4,
	SLOT_PUSH_TYPE_MOUSE_LEFT,
	SLOT_PUSH_TYPE_MOUSE_RIGHT,
	SLOT_PUSH_TYPE_END
};

enum FOLLOWER_TYPE
{
	FOLLOWER_TYPE_ENCHANTRESS,
	FOLLOWER_TYPE_END
};

enum GATE_WAY_TYPE
{
	GATE_WAY_TYPE_TRISTREAM,
	GATE_WAY_TYPE_TRISTREAM_FIELD,
	GATE_WAY_TYPE_CATHEDRAL_F1,
	GATE_WAY_TYPE_CATHEDRAL_F2,
	GATE_WAY_TYPE_CATHEDRAL_F3,
	GATE_WAY_TYPE_CATHEDRAL_F4,
	GATE_WAY_TYPE_ROYAL_CHAMBER,
	GATE_WAY_TYPE_END
};